### ISSUE TITLE
Nuclues 2.5.0 Tray menu throws exception on Win11

### ISSUE THREAD

**Issue by janbarari** [kdroidFilter/Nucleus#594]
## 🐛 Describe the bug
It seems using Tray in version 2.5.0 throws exception, It was working on 2.4.7 without any change.

Stacktrace
```
java.lang.NoSuchMethodError: 'org.jetbrains.skia.Data org.jetbrains.skia.Image.encodeToData$default(org.jetbrains.skia.Image, org.jetbrains.skia.EncodedImageFormat, int, int, java.lang.Object)'
	at dev.nucleusframework.composenativetray.utils.ComposableIconUtils.renderComposableToPngBytes(ComposableIconUtils.kt:101)
	at dev.nucleusframework.composenativetray.utils.ComposableIconUtils.calculateContentHash(ComposableIconUtils.kt:228)
	at dev.nucleusframework.composenativetray.tray.api.NativeTrayKt.Tray(NativeTray.kt:558)
	at dev.nucleusframework.composenativetray.tray.api.ComposableTrayKt.Tray(ComposableTray.kt:52)
```

How i used (Using compose 1.12.0-rc01)
```
Tray(
        icon = painterResource(Res.drawable.favicon),
        tooltip = stringResource(Res.string.app_name),
        primaryAction = {
            isWindowVisible = true
        },
    ) {
        Item(label = stringResource(Res.string.open_app)) { isWindowVisible = true }
        Divider()
        Item(label = stringResource(Res.string.quit)) { exitApplication() }
    }
```

## 📱 Tech info
 - Device: AMD x64
 - OS: Win11
 - Library/App version: 2.5.0

**Comment by kdroidFilter** [comment]
Yes, indeed, I need to update Compose Native Tray to support the new version of Skiko.
